# Day 4 (10-April-2021)

## ML Foundations: A story on generalization by [Hanie Sedghi](https://research.google/people/HanieSedghi/) 9 AM

Hanie focuses on generalization in DL models and what plays a role in it. She first shows the work on proving generalization bounds in terms of training loss, number of parameters, Lipschitz constant, and distance from the initial weights. She shows that network criticality is mostly capturing the generalization error in well-known CNN models. 

Hanie introduces a new lens called "Deep Bootstrap" for measuring generalization error where test error is captured in an ideal world (generative model) and the real world (actual data) and compared. One should expect it to be the lowest if the model is generalizing well on the real data. She shows some experimental results on NN models with this technique. 

After this, Hanie covers what is transferred in transfer learning. 

## Overview of research at Google Research India by [Manish Gupta](https://research.google/people/106704)

Manish starts with four different areas where the research is focused: i) Pure research; ii) infrastructure buildup; iii) Product engagements; iv) New product innovations.

Manish gives an introduction and overview of various teams and team members at Google. After that, he answers the queries related to internship and full-time opportunities at Google research, India. 

## Closing Keynote by [Cordelia Schmid](https://research.google/people/CordeliaSchmid/) [YouTube link](https://www.youtube.com/watch?v=PGod_csWSX0)

Cordelia gives a brief talk on machine vision perception. She explains a novel method of creating synthetic datasets of human activities. She also explains a model called VideoBERT for video predictions. The talk ends with a detailed Q&A on the vision topic.